version: "3"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=3000
    ports:
      - "8080:3000"

  redis:
    image: "redis:latest"
    environment:
      - REDIS_ADDRESS=localhost
      - REDIS_PORT=6379

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
