version: "3"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # Specify the target stage in the Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    build:
      context: .
      dockerfile: Dockerfile
      target: redis # Specify the target stage in the Dockerfile
    ports:
      - "6379:6379"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
